package org.exolin.citysim.ui.sp;

import java.awt.Image;
import java.awt.Window;
import java.math.BigDecimal;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Thomas
 */
public class PlantInfoDialog extends javax.swing.JDialog
{
    /**
     * Creates new form PlantInfoDialog
     * @param parent
     * @param title
     * @param buildingCost
     * @param megaWatt
     * @param maintenance
     */
    public PlantInfoDialog(Window parent, String title, int buildingCost, int megaWatt, BigDecimal maintenance, Image image)
    {
        super(parent, ModalityType.DOCUMENT_MODAL);
        setTitle(title);
        initComponents();
        
        imageLabel.setIcon(new ImageIcon(image));
        imageLabel.setHorizontalAlignment(JLabel.CENTER);
        imageLabel.setVerticalAlignment(JLabel.CENTER);
        
        buildingCostValueLabel.setText(Integer.toString(buildingCost)+" $");
        mwValueLabel.setText(Integer.toString(megaWatt));
        maintenanceValueLabel.setText(maintenance+" $");
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        imageLabel = new javax.swing.JLabel();
        propPanel = new javax.swing.JPanel();
        labelPanel = new javax.swing.JPanel();
        mwLabel = new javax.swing.JLabel();
        buildingCostLabel = new javax.swing.JLabel();
        maintenanceLabel = new javax.swing.JLabel();
        propertiesPanel = new javax.swing.JPanel();
        mwValueLabel = new javax.swing.JLabel();
        buildingCostValueLabel = new javax.swing.JLabel();
        maintenanceValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().add(imageLabel, java.awt.BorderLayout.CENTER);

        propPanel.setLayout(new java.awt.BorderLayout());

        labelPanel.setLayout(new java.awt.GridLayout(0, 1));

        mwLabel.setText("MW:");
        labelPanel.add(mwLabel);

        buildingCostLabel.setText("Building Cost:");
        labelPanel.add(buildingCostLabel);

        maintenanceLabel.setText("Maintenance:");
        labelPanel.add(maintenanceLabel);

        propPanel.add(labelPanel, java.awt.BorderLayout.LINE_START);

        propertiesPanel.setLayout(new java.awt.GridLayout(0, 1));

        mwValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mwValueLabel.setText("jLabel1");
        propertiesPanel.add(mwValueLabel);

        buildingCostValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        buildingCostValueLabel.setText("jLabel1");
        propertiesPanel.add(buildingCostValueLabel);

        maintenanceValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        maintenanceValueLabel.setText("jLabel1");
        propertiesPanel.add(maintenanceValueLabel);

        propPanel.add(propertiesPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(propPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildingCostLabel;
    private javax.swing.JLabel buildingCostValueLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JLabel maintenanceLabel;
    private javax.swing.JLabel maintenanceValueLabel;
    private javax.swing.JLabel mwLabel;
    private javax.swing.JLabel mwValueLabel;
    private javax.swing.JPanel propPanel;
    private javax.swing.JPanel propertiesPanel;
    // End of variables declaration//GEN-END:variables
}
