package org.exolin.citysim.ui.sp;

import java.awt.Image;
import java.awt.Window;
import java.math.BigDecimal;
import javax.swing.ImageIcon;

/**
 *
 * @author Thomas
 */
public class PlantInfoDialog extends javax.swing.JDialog
{
    /**
     * Creates new form PlantInfoDialog
     * @param parent
     * @param title
     * @param buildingCost
     * @param megaWatt
     * @param maintenance
     */
    public PlantInfoDialog(Window parent, String title, int buildingCost, int megaWatt, BigDecimal maintenance, Image image)
    {
        super(parent, ModalityType.DOCUMENT_MODAL);
        setTitle(title);
        initComponents();
        imageLabel.setIcon(new ImageIcon(image));
        buildingCostValueLabel.setText(Integer.toString(buildingCost)+" $");
        mwValueLabel.setText(Integer.toString(megaWatt));
        maintenanceValueLabel.setText(maintenance+" $");
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        mwLabel = new javax.swing.JLabel();
        mwValueLabel = new javax.swing.JLabel();
        buildingCostLabel = new javax.swing.JLabel();
        buildingCostValueLabel = new javax.swing.JLabel();
        maintenanceLabel = new javax.swing.JLabel();
        maintenanceValueLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        mwLabel.setText("MW:");

        mwValueLabel.setText("jLabel1");

        buildingCostLabel.setText("Building Cost:");

        buildingCostValueLabel.setText("jLabel1");

        maintenanceLabel.setText("Maintenance:");

        maintenanceValueLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(mwLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mwValueLabel))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(buildingCostLabel)
                            .addGap(18, 18, 18)
                            .addComponent(buildingCostValueLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maintenanceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(maintenanceValueLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mwLabel)
                    .addComponent(mwValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildingCostLabel)
                    .addComponent(buildingCostValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maintenanceLabel)
                    .addComponent(maintenanceValueLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);
        getContentPane().add(imageLabel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buildingCostLabel;
    private javax.swing.JLabel buildingCostValueLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel maintenanceLabel;
    private javax.swing.JLabel maintenanceValueLabel;
    private javax.swing.JLabel mwLabel;
    private javax.swing.JLabel mwValueLabel;
    // End of variables declaration//GEN-END:variables
}
