package org.exolin.citysim.ui.sp;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author Thomas
 */
public class SelectorPanel2 extends javax.swing.JPanel
{

    /**
     * Creates new form SelectorPanel2
     */
    public SelectorPanel2()
    {
        initComponents();
    }
    
    public static void main(String[] args)
    {
        JFrame f = new JFrame();
        f.add(new SelectorPanel2(), BorderLayout.CENTER);
        f.pack();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(0, 1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/bulldoze.png"))); // NOI18N
        jPanel1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/tree_water.png"))); // NOI18N
        jPanel1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/emergency.png"))); // NOI18N
        jPanel1.add(jButton3);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/electricity.png"))); // NOI18N
        jPanel2.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/water.png"))); // NOI18N
        jPanel2.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/city_hall.png"))); // NOI18N
        jPanel2.add(jButton6);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/street.png"))); // NOI18N
        jPanel3.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/rail.png"))); // NOI18N
        jPanel3.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/port.png"))); // NOI18N
        jPanel3.add(jButton9);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/residential.png"))); // NOI18N
        jPanel4.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/business.png"))); // NOI18N
        jPanel4.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/industry.png"))); // NOI18N
        jButton12.setToolTipText("");
        jPanel4.add(jButton12);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout());

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/school.png"))); // NOI18N
        jPanel5.add(jButton13);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/police.png"))); // NOI18N
        jButton14.setToolTipText("");
        jPanel5.add(jButton14);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exolin/citysim/menu/party.png"))); // NOI18N
        jPanel5.add(jButton15);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
