package org.exolin.citysim;

/**
 *
 * @author Thomas
 */
public class GameData extends javax.swing.JPanel implements GamePanelListener
{

    /**
     * Creates new form GameData
     */
    public GameData()
    {
        initComponents();
    }

    @Override
    public void zoomChanged(int zoom)
    {
        zoomValueLabel.setText(zoom+"");
    }

    @Override
    public void offsetChanged(int xoffset, int yoffset)
    {
        offsetValueLabel.setText(xoffset+"/"+yoffset);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        zoomValueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        offsetValueLabel = new javax.swing.JLabel();

        jLabel1.setText("Zoom:");

        zoomValueLabel.setText("undefined");
        zoomValueLabel.setName(""); // NOI18N

        jLabel2.setText("Offset:");

        offsetValueLabel.setText("undefined");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zoomValueLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(offsetValueLabel)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(zoomValueLabel)
                    .addComponent(jLabel2)
                    .addComponent(offsetValueLabel))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel offsetValueLabel;
    private javax.swing.JLabel zoomValueLabel;
    // End of variables declaration//GEN-END:variables
}
