package org.exolin.citysim.ui;

import java.awt.Point;
import java.awt.event.KeyEvent;

/**
 *
 * @author Thomas
 */
public class GameDataPanel extends javax.swing.JPanel
{
    private GamePanel panel;
    
    /**
     * Creates new form GameData
     */
    public GameDataPanel()
    {
        initComponents();
    }

    public void setPanel(GamePanel panel)
    {
        this.panel = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        resetPositionLabel = new javax.swing.JLabel();
        keyLeftLabel = new javax.swing.JLabel();
        keyTopLabel = new javax.swing.JLabel();
        keyBottomLabel = new javax.swing.JLabel();
        keyRightLabel = new javax.swing.JLabel();

        resetPositionLabel.setText("Reset position");
        resetPositionLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                resetPositionLabelMouseClicked(evt);
            }
        });

        keyLeftLabel.setText("<");
        keyLeftLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                keyLeftLabelMousePressed(evt);
            }
        });

        keyTopLabel.setText("^");
        keyTopLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                keyTopLabelMousePressed(evt);
            }
        });

        keyBottomLabel.setText("v");
        keyBottomLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                keyBottomLabelMousePressed(evt);
            }
        });

        keyRightLabel.setText(">");
        keyRightLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                keyRightLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resetPositionLabel)
                .addGap(31, 31, 31)
                .addComponent(keyLeftLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keyTopLabel)
                    .addComponent(keyBottomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyRightLabel)
                .addContainerGap(567, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(keyTopLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(keyBottomLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(resetPositionLabel)
                                .addComponent(keyLeftLabel))
                            .addComponent(keyRightLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetPositionLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_resetPositionLabelMouseClicked
    {//GEN-HEADEREND:event_resetPositionLabelMouseClicked
        panel.resetPosition();
    }//GEN-LAST:event_resetPositionLabelMouseClicked

    private void keyLeftLabelMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_keyLeftLabelMousePressed
    {//GEN-HEADEREND:event_keyLeftLabelMousePressed
        panel.keyPressed(KeyEvent.VK_LEFT);
    }//GEN-LAST:event_keyLeftLabelMousePressed

    private void keyTopLabelMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_keyTopLabelMousePressed
    {//GEN-HEADEREND:event_keyTopLabelMousePressed
        panel.keyPressed(KeyEvent.VK_UP);
    }//GEN-LAST:event_keyTopLabelMousePressed

    private void keyBottomLabelMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_keyBottomLabelMousePressed
    {//GEN-HEADEREND:event_keyBottomLabelMousePressed
        panel.keyPressed(KeyEvent.VK_DOWN);
    }//GEN-LAST:event_keyBottomLabelMousePressed

    private void keyRightLabelMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_keyRightLabelMousePressed
    {//GEN-HEADEREND:event_keyRightLabelMousePressed
        panel.keyPressed(KeyEvent.VK_RIGHT);
    }//GEN-LAST:event_keyRightLabelMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel keyBottomLabel;
    private javax.swing.JLabel keyLeftLabel;
    private javax.swing.JLabel keyRightLabel;
    private javax.swing.JLabel keyTopLabel;
    private javax.swing.JLabel resetPositionLabel;
    // End of variables declaration//GEN-END:variables
}
