package org.exolin.citysim.ui.budget;

import java.math.BigDecimal;
import java.util.Optional;

/**
 *
 * @author Thomas
 */
public class BudgetLinePanel extends javax.swing.JPanel
{
    private final Optional<Boolean> isIncome;
    private BigDecimal taxRevenue = BigDecimal.ZERO;
    private BigDecimal expenses = BigDecimal.ZERO;

    /**
     * Creates new form BudgetLinePanel
     * @param title
     * @param isIncome
     */
    public BudgetLinePanel(String title, Optional<Boolean> isIncome)
    {
        this.isIncome = isIncome;
        initComponents();
        titleLabel.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        incomeLabel = new javax.swing.JLabel();
        expenseLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        incomeLabel.setForeground(new java.awt.Color(0, 204, 0));
        incomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        incomeLabel.setText("income");
        incomeLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        jPanel1.add(incomeLabel);

        expenseLabel.setForeground(new java.awt.Color(255, 51, 51));
        expenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expenseLabel.setText("expense");
        expenseLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        jPanel1.add(expenseLabel);

        add(jPanel1, java.awt.BorderLayout.EAST);

        titleLabel.setText("Title");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        add(titleLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel expenseLabel;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    void resetValues()
    {
        taxRevenue = BigDecimal.ZERO;
        expenses = BigDecimal.ZERO;
    }

    void updateValues(BigDecimal taxRevenue, BigDecimal maintenance)
    {
        this.taxRevenue = this.taxRevenue.add(taxRevenue);
        this.expenses = this.expenses.add(maintenance);
    }

    void showValues()
    {
        incomeLabel.setText(getText(taxRevenue, !isIncome.orElse(true)));
        expenseLabel.setText(getText(expenses, isIncome.orElse(false)));
    }

    private String getText(BigDecimal expenses, boolean zeroIsEmpty)
    {
        if(expenses.equals(BigDecimal.ZERO) && zeroIsEmpty)
            return "";
        
        return expenses.toPlainString();
    }

    public BigDecimal getTaxRevenue()
    {
        return taxRevenue;
    }

    public BigDecimal getExpenses()
    {
        return expenses;
    }
}
