package org.exolin.citysim.ui.budget;

import java.math.BigDecimal;
import org.exolin.citysim.model.World;

/**
 *
 * @author Thomas
 */
public class DiffPanel extends javax.swing.JPanel
{
    /**
     * Creates new form DiffPanel
     */
    public DiffPanel()
    {
        initComponents();
    }
    
    void update(World w, BigDecimal taxRevenue, BigDecimal expenses)
    {
        BigDecimal start = w.getMoney();
        currentBalanceLabel.setText(start.toString());
        incomeLabel.setText(taxRevenue.toString());
        expenseLabel.setText(expenses.toString());
        afterLabel.setText(start.add(taxRevenue).subtract(expenses).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        currentBalanceLabel = new javax.swing.JLabel();
        incomeLabel = new javax.swing.JLabel();
        expenseLabel = new javax.swing.JLabel();
        afterLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 10));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("Current balance:");
        jPanel2.add(jLabel1);

        jLabel2.setText("Income:");
        jPanel2.add(jLabel2);

        jLabel3.setText("Expense:");
        jPanel2.add(jLabel3);

        jLabel4.setText("After:");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        currentBalanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentBalanceLabel.setText("jLabel5");
        jPanel3.add(currentBalanceLabel);

        incomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        incomeLabel.setText("jLabel6");
        jPanel3.add(incomeLabel);

        expenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        expenseLabel.setText("jLabel7");
        jPanel3.add(expenseLabel);

        afterLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        afterLabel.setText("jLabel8");
        jPanel3.add(afterLabel);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afterLabel;
    private javax.swing.JLabel currentBalanceLabel;
    private javax.swing.JLabel expenseLabel;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
